name: 'Backport'
description: 'Backport hotfix onto other environment branches.'
author: 'Juraj Piar <juraj.piar@icloud.com>'
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
  branches:
    description: Branches for backporting
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
